### ISSUE TITLE
wandb error

### ISSUE THREAD

**Issue by ycimtay** [DeepMicroscopy/MIDOGpp#1]
When run (main.py) we got an error related to the following line:
run = wandb.init(entity=cfg.wandb.entity, project=cfg.wandb.project,
                         config=OmegaConf.to_container(cfg, resolve=True, throw_on_missing=True), reinit=True)

Error msg:wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)

How to get an access, normally we created our own account on wandb however I think the credentials should be provided for us. Could you please help ?

Best Wishes.

**Comment by FraukeWilm** [comment]
Thank you for your interest in our dataset. Wandb is used for tracking the training progress and saving model checkpoints. This can be done in your own account on wandb. You have to adapt the configuration file of the project accordingly, i.e. replace _entity: username_ with your wandb username

![image](https://github.com/DeepMicroscopy/MIDOGpp/assets/38855399/d0a3f9e2-4f11-41f5-8c0f-5aa4e478acc3)

Kind regards,
Frauke
