### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'fetchall'

### ISSUE THREAD

**Issue by trinhvg** [DeepMicroscopy/MIDOGpp#3]
Hello, I have an error in the slide hepper file when I run:
 42  getslides = """SELECT uid, filename, width, height FROM Slides"""
  43  for currslide, file_name, width, height in tqdm(database.execute(getslides).fetchall()):
  
  The error shows:
Warning: DB not opened.
      for currslide, file_name, width, height in tqdm(database.execute(getslides).fetchall()):
AttributeError: 'NoneType' object has no attribute 'fetchall'

I use the same SlideRunner versions =2.0. Please helps.

**Comment by maubreville** [comment]
Hey there. 
DB not opened is typically a sign that the DB is not in the place where it was expected to be. 
Please check the path to the sqlite file.
Best,
Marc
