### ISSUE TITLE
Download of .json and .sqlite in Setup.ipynb fails

### ISSUE THREAD

**Issue by luzuku** [DeepMicroscopy/MIDOGpp#4]
Running the current `Setup.ipynb` fails for the last two files, namely:
 ```
'40283737': 'MIDOGpp.json',
'40283743': 'MIDOGpp.sqlite'
```

with `HTTPError: HTTP Error 404: Not Found`.

But I believe you already have these [two files in the repo](https://github.com/DeepMicroscopy/MIDOGpp/tree/main/databases) anyways right?

**Comment by maubreville** [comment]
Hey Lennard,

exactly, the files are already in the repo. It's unfortunate, however, that the setup script won't execute flawlessly.

Best,

Marc
