### ISSUE TITLE
Canine soft tissue sarcoma in Humans?

### ISSUE THREAD

**Issue by luzuku** [DeepMicroscopy/MIDOGpp#5]
The file `MIDOGpp/datasets_xvalidation.csv` contains items that have `Species==Human` and `Tumor==canine soft tissue sarcoma` at the same time. Is this right?

```python
import pandas as pd
df = pd.read_csv("MIDOGpp/datasets_xvalidation.csv", sep=";")
human = df[df.Species == "Human"]
print(human.Tumor.value_counts(dropna=False))
```

```
human breast cancer           150
canine soft tissue sarcoma    100
human neuroendocrine tumor     55
human melanoma                 49
Name: Tumor, dtype: int64
```

**Comment by FraukeWilm** [comment]
Hi, thanks for pointing that out. Of course, the CSTS samples are from canines. We have corrected the .csv file accordingly.
