### ISSUE TITLE
Output Format

### ISSUE THREAD

**Issue by FabianHoerst** [DeepMicroscopy/MIDOGpp#7]
Hello, 

I have a question regarding the evaluation code. Is the expected format for the ground-truth and the predictions the same as for MIDOG 2022 stated here: https://imig.science/midog2021/2021/08/18/a-note-on-the-json-output-format/ ?
Additionally, is there one json file required for each image also in the ground-truth or is there just one gt file for all images?

Thanks in advance!

**Comment by FraukeWilm** [comment]
Hi Fabian,

Thank you for your interest in our work. Yes, the expected format is similar to the MIDOG 2022 challenge, but all results can be collected in one file. Here are exemplary prediction and ground truth files:

prediction.json
{"006.tiff": {"type": "Multiple points", "points": [{"point": [1.005661110971888, 0.739815690252091, 0], "probability": 0.8512454628944397, "name": "mitotic figure"}, {"point": [0.8942733554454301, 1.0470818227635212, 0], "probability": 0.8236722946166992, "name": "mitotic figure"}], "version": {"major": 1, "minor": 0}}, "007.tiff": {"type": "Multiple points", "points": [{"point": [1.2690968026956404, 0.7248881579016242, 0], "probability": 0.9075098633766174, "name": "mitotic figure"}, {"point": [0.8143148564346692, 0.06361628893807421, 0], "probability": 0.8529996871948242, "name": "mitotic figure"}], "version": {"major": 1, "minor": 0}}}

ground-truth.json
{"006.tiff": [[0.15932994742938608, 0.3553238884433752, 0], [0.16860910629956338, 0.3813507974694823, 0]], "007.tiff": [[0.5951777738073968, 0.165642308379489, 0]]}


Kind regards,
Frauke

**Comment by FabianHoerst** [comment]
Thank you for clarifying and the fast answer!
