### ISSUE TITLE
Question regarding evaluation function (minor bug?)

### ISSUE THREAD

**Issue by FabianHoerst** [DeepMicroscopy/MIDOGpp#8]
Hello,

i think there might be a bug in the evaluation code or I might missunderstand something: In the evaluation function, first, the tuple is [x,y,z,label,score]. However, for creating the pred_dict, it is referenced as [x,y,z,score,label]. Why is the label used as score here? 
https://github.com/DeepMicroscopy/MIDOGpp/blob/c2726b1f40a1bfe4f0acce9c7f1d186eec12e914/evaluation.py#L86-L94

**Comment by maubreville** [comment]
Hey Fabian. 

Thanks for that. We'll look into it.

Best,

Marc

**Comment by FraukeWilm** [comment]
Dear Fabian,

Yes, this was indeed a bug in our evaluation code which influenced the mAP calculation. Thank you for brining this to our attention. We have made the necessary code changes and will prepare an addendum for our manuscript. Fortunately, all evaluations in the manuscript were based on the F1 score, which was not affected by the bug. 


Kind regards,
Frauke

**Comment by FabianHoerst** [comment]
Thank you for the response!

Sorry for the problem it may have caused! Luckily, your mAP results should get even better with the change.
Best, Fabian

**Comment by shikha-gist** [comment]
have you updated the evaluation code in the current repo?

**Comment by FraukeWilm** [comment]
Yes. As stated above, we have adapted the evaluation code.
