### ISSUE TITLE
Is Figshare down ?

### ISSUE THREAD

**Issue by paraynaud** [DeepMicroscopy/MIDOGpp#9]
Hello,

I tried to download the dataset by following the instructions 
```python
from urllib.request import urlretrieve
import os
from tqdm import tqdm

for file in tqdm(filename):
    url = f'https://figshare.com/ndownloader/files/{file}?private_link=bcb4228247770ff4e03e'
    local_filename, headers  = urlretrieve(url, 'images'+os.sep+filename[file])
```
without success.

I obtain the error:
```
...python
  0%|                                                                                                                                                            | 0/505 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "C:\Users\dev\anaconda3\envs\MIDOG\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\dev\anaconda3\envs\MIDOG\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\dev\anaconda3\envs\MIDOG\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\dev\anaconda3\envs\MIDOG\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\dev\anaconda3\envs\MIDOG\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\dev\anaconda3\envs\MIDOG\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\dev\anaconda3\envs\MIDOG\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

I assume that the Figshare is down because I can't access any page, e.g.:
```python
https://figshare.com/ndownloader/files/40283740?private_link=bcb4228247770ff4e03e # (images\553.tiff )
```
while the following code 
```
local_filename, headers = urllib.request.urlretrieve('http://python.org/')
html = open(local_filename)
html.close()
```
operates properly.

Is it just for me, or can you replicate the issue as well ?

**Comment by maubreville** [comment]
Hey there.

It seems they have changed the URL syntax. Could you try and remove the ?private_link part and confirm it works? I did it for the link you mentioned above and it seems to work fine. If yes, then we'll change the script.

Best,

Marc

**Comment by paraynaud** [comment]
Thanks a lot for the help Marc.
With your advice, I succeeded in downloading all the .tiff files, but not the two last files: `'40283737': 'MIDOGpp.json', '40283743': 'MIDOGpp.sqlite'`.
I tried combination with or without `?` and `private_link` without success.

Any idea ?

PS : I will open a PR to fix this when I'm done with the downloading.

**Comment by maubreville** [comment]
I think I would then just push those files to the repository. Unfortunately I am on the go right now.

could you try to fetch the file here using the browser? https://springernature.figshare.com/articles/dataset/MIDOG_database_as_JSON_format/23531121?backTo=%2Fcollections%2FMIDOG_A_Comprehensive_Multi-Domain_Dataset_for_Mitotic_Figure_Detection%2F6615571&file=41265615

Best

Marc

**Comment by paraynaud** [comment]
This is my bad on this one, those two are already present in the repo (in `dataset/`).
I just reacted to what the `setup.py` script said to me.
I will remove them from being downloaded in my PR.

**Comment by maubreville** [comment]
Thanks a lot!

**Comment by paraynaud** [comment]
You're welcome, thanks for your help as well.
I'm trying to replicate your results, so I will probably have more questions in the future.
If I can help you during this time by writing PRs, it will be my pleasure !

**Comment by maubreville** [comment]
Thanks a lot! Always great to see other people reproduce out results. Let me know if you encounter more issues.
